<a href="https://www.kaggle.com/code/rimon394/mlb-2-class-5-assignment-rimon?scriptVersionId=346997386" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [5]:
#1D array

x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
#2D array
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#3D array
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [8]:
#1D array using arange() and reshape()
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#2D array using arange() and reshape()
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#3D array using arange() and reshape()
np.arange(27).reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
#4D array using arange() and reshape()
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

# create array using ones and zeros

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# using random

In [14]:
# this is a 3*3 random matrics 
#np.random.random((3,3))*20 this is random its uggly
np.round(np.random.random((3,3))*20)

array([[15.,  6., 11.],
       [ 5.,  6.,  1.],
       [ 0.,  6., 18.]])

# using linspace

In [15]:
np.linspace(10,100,5)   # (start,total,space)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [16]:
np.linspace(10,100,5,dtype=int)  ##  convertion the type of the value in integer 

array([ 10,  32,  55,  77, 100])

# create 1D array of tip from tips dataframe

In [17]:
tips.head()


,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [18]:
tip=tips['tip'].to_numpy()
print(tip)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [19]:
tips[['tip','total_bill']].to_numpy()

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [20]:
data=tips[['tip','total_bill']].to_numpy()
data

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

In [21]:
data.ndim

2

In [22]:
data.shape

(244, 2)

In [23]:
np.size(data)

488

In [24]:
data.itemsize

8

# change data type and memory size of any np-array using astype()

In [25]:
data = data.astype(np.float32)
data.itemsize

4

# create 2 same dimensional array and do scalar and vector operations

In [26]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# find minimun and maximum tip

In [29]:
tip=tips['tip'].to_numpy()
print(tip)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

In [30]:
np.min(tip)

np.float64(1.0)

In [31]:
np.max(tip)

np.float64(10.0)

# find average total_bill and average tip

In [32]:
np.mean(tip)

np.float64(2.99827868852459)

In [33]:
bill=tips['total_bill'].to_numpy()
print(bill)

[16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.81 17.

In [34]:
np.mean(bill)

np.float64(19.78594262295082)

# find median total_bill

In [35]:
np.median(bill)

np.float64(17.795)

# find standard deviasion and variance of tip

In [36]:
np.std(tip)

np.float64(1.3807999538298954)

In [37]:
np.var(tip)

np.float64(1.9066085124966412)

# find log values of tip

# apply round, floor and ceil operation on tip array

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

# stacking and spliting

In [38]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

# use hsplit() and vsplit()